### ISSUE TITLE
table 27: OCR504_ICSW sensor, remove satlantic reference

### ISSUE THREAD

**Issue by tcarval** [nvs-vocabs/R27#11]
An OCR multispectral radiometer SENSOR_MODEL is currently "SATLANTIC_OCR504_ICSW" in reference table 27.
SeaBird Electronics acquired both Wetlabs and Satlantic years back, so Seabird Scientific (SBS) encompasses all three sensor makers.

**Proposal:** add a new sensor model "OCR504_ICSW" with no mention of the sensor maker.

**Status:** approved, tables 26 and 27 updated on 2021-27-12

**Comment:** depending on date of purchase of the sensor (before or after SBS acquisition) use these terms:
Before SATLANTIC acquisition by SBS:
- SATLANTIC_OCR504_R10W
- SATLANTIC_OCR507_ICSW
- SATLANTIC_OCR507_R10W
- SATLANTIC_OCR507_ICSWR10W
- SATLANTIC_PAR

After SATLANTIC acquisition by SBS:
- OCR504_R10W
- OCR507_ICSW
- OCR507_R10W
- OCR507_ICSWR10W
- PAR

**Comment by apswong** [comment]
Hello, @tcarval @vpaba
I thought the agreement at the ADMT was that both "SATLANTIC_OCR504_ICSW" and "OCR504_ICSW" would exist in Ref Table 27, so that DACs can use either entry, depending on date of purchase of the sensor (before or after SBS acquisition).  In other words, "SATLANTIC_OCR504_ICSW" (and other "SATLANTIC_***" sensor models) should **not** be deprecated in Ref Table 27.

**Comment by vpaba** [comment]
@apswong this was my understanding too.

**Comment by tcarval** [comment]
Hello, @vpaba @apswong 
Yes, this is correct, I just updated the first message of this issue,  "OCR504_ICSW" is now valid, the current SATLANTIC_* terms remain valid and should not be "deprecated" .

**Comment by tcarval** [comment]
Hello Claudia,
Here are corrections needed on your metadata files, taking into account the additions in table 26 and 27.
The file format checker should be updated within a few days.

grep -i \<error\> $WRK/out/*
**Replace "SBE" with "Sea-Bird Scientific"**
5906320_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[4]: Inconsistent: 'OCR504_ICSW'/'SBE'</error>
5906320_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[5]: Inconsistent: 'OCR504_ICSW'/'SBE'</error>
5906320_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'OCR504_ICSW'/'SBE'</error>
5906320_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[7]: Inconsistent: 'OCR504_ICSW'/'SBE'</error>
5906446_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[4]: Inconsistent: 'OCR504_ICSW'/'SBE'</error>
5906446_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[5]: Inconsistent: 'OCR504_ICSW'/'SBE'</error>
5906446_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'OCR504_ICSW'/'SBE'</error>
5906446_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[7]: Inconsistent: 'OCR504_ICSW'/'SBE'</error>

**Replace "MBARI" with "SBE"**
5906448_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'SEAFET'/'MBARI'</error>
5906449_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'SEAFET'/'MBARI'</error>
5906450_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'SEAFET'/'MBARI'</error>
5906468_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'SEAFET'/'MBARI'</error>
5906469_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'SEAFET'/'MBARI'</error>
5906470_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'SEAFET'/'MBARI'</error>
5906471_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'SEAFET'/'MBARI'</error>
5906473_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'SEAFET'/'MBARI'</error>
5906474_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'SEAFET'/'MBARI'</error>
5906476_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'SEAFET'/'MBARI'</error>

**Existing KELLER model : "KELLER_PA8"**
5906418_meta.nc.filecheck:    <error>SENSOR_MODEL[1]: 'unknown' Status: Invalid</error>

**Replace "RBR" with "DRUCK"**
5906457_meta.nc.filecheck:    <error>SENSOR_MODEL/SENSOR_MAKER[3]: Inconsistent: 'DRUCK_2900PSIA'/'RBR'</error>

**Comment by tcarval** [comment]
Hello @vpaba , can you add Claudia and Mark in the nvs-vocab members ?

**Comment by tcarval** [comment]
**Message from Claudia**
Hi Thierry,
I looked at the format checker comparison.
There, OCR504_ICSW is listed with "Sea-Bird Scientific" instead of SBE,
but NVS seems to say it should be SBE.
Please review this and let me know what it should be (seems to me one or
the other needs to change).

**Answer from Thierry**
« Sea-Bird Scientific » is the name that is now communicated on Seabird web site (https://www.seabird.com).
The consensus in ADMT-22 was to use the brands and models as communicated by the companies.
So “SBE” remains the name for Seabird sensors existing entries.
New sensor entries should use “Sea-Bird Scientific”.
That is conservative (we do not change existing sensor entries), still evolutive (new sensor entries use the most recent brand and model).
