### ISSUE TITLE
Request for addition of new SENSOR_MODEL: SBE41N_V5.3.5

### ISSUE THREAD

**Issue by ksato-aopc** [nvs-vocabs/R27#12]
Hello. We JAMSTEC have deployed a float equipped with SBE41N_V5.3.5 in this year. It is the new version of SBE41N. So, would you add it to the reference table, whose identifier is 'R27'?
Thank you. Kanako

**Comment by vturpin** [comment]
What is the process now @vpaba ? 
How can we make things goes fast regarding this new sensor model ?
Does we have to validate something from OceanOPS side / GItHub member side ?
FYI we will add this model to our reference list at OceanOPS today.

**Comment by tcarval** [comment]
Done, SBE41N_V5.3.5 is now accepted
