### ISSUE TITLE
Request for addition of new SENSOR_MODEL: SBE61_V5.0.3

### ISSUE THREAD

**Issue by ksato-aopc** [nvs-vocabs/R27#3]
We JAMSTEC have deployed a Deep APEX equipped with SBE61_V5.0.3 in this year. It is the new version of SBE61. So, would you add it to the reference table, whose identifier is 'R27'?

**Comment by vpaba** [comment]
Hello, thanks for submitting this new issue. As it is an R27-specific query, I have transferred it under the R27 repository - I hope it is ok. I will notify you as soon as I have added this entry to R27.  @mscanderbeg, would it be possible for you to update the Google spreadsheet with this addition please? Thanks, Violetta

**Comment by vpaba** [comment]
Hi @ksato-aopc, this sensor firmware version was added to R27. Please note it may take up to 24h for new entries to be visible on the NVS web interface: http://vocab.nerc.ac.uk/search_nvs/R27/.
Thanks, Violetta

**Comment by ksato-aopc** [comment]
Thank you for your support. I have confirmed that there is 'SBE61_V5.0.3' in http://vocab.nerc.ac.uk/search_nvs/R27/.
Kanako SATO

**Comment by mscanderbeg** [comment]
Hello,

 

I’ve added this to the Google spreadsheet version of the Argo ref tables.

 

Thanks,

megan

**Comment by vpaba** [comment]
Thank you, closing the issue.
