### ISSUE TITLE
Additional details needed on RBR_PRES and RBR_PRESA pressure sensor models

### ISSUE THREAD

**Issue by vpaba** [nvs-vocabs/R27#5]
I sent an email to RBR, asking to confirm that the 'RBR_PRES' model is the pressure sensor part of the RBRargo CTD, whereas the RBR_PRESA is the pressure sensor part of the RBRargo3 CTD.

**Comment by ClareBellingham** [comment]
[https://usgodae.org/pub/outgoing/argo/etc/FileChecker/RESULTS/2021-03_results/meta-files.errors](url)

The GDAC filechecker rejects RBR_PRESA and a named pressure sensor maker (as in Keller in this instance) <error>SENSOR_MODEL/SENSOR_MAKER[1]: Inconsistent: 'RBR_PRESA'/'KELLER'</error>

**Comment by matdon17** [comment]
There is a question as to whether RBR_PRES and RBR_PRESA should be retired in favour of specific sensor models, such as KELLER_PA8 and KELLER_PA7L, see https://github.com/nvs-vocabs/R27/issues/6

**Comment by ClareBellingham** [comment]
using RBR_PRES and RBR_PRESA is inconsistent with the way other pressure sensors are reported in the Argo system and does not then allow models to undergo any kind of evaluation of RBR pressure sensors without updating them in the future.  Also KELLER_PA8 is in the reference tables and so presumably being used by another DAC already

**Comment by matdon17** [comment]
As per discussions with a wider group by email, the entries have been agreed to be "RBR_PRES" and "RBR_PRES_A" (note the second underscore).  "RBR_PRESA" was a typing error and needs correcting in the Google Spreadsheet.

I have attached the document that was compiled which outlines what is meant to be implemented.
[JCOMMOPS & DAC RBRargoRBRargo³ Metadata v2.pdf](https://github.com/nvs-vocabs/R27/files/6460714/JCOMMOPS.DAC.RBRargoRBRargo.Metadata.v2.pdf)

The remaining issue as far as I can tell is what is the distinguishing features of an RBR_PRES and an RBR_PRES_A sensor to enable a definition to be written for it?

@vpaba can you advise if this information is still outstanding?
