### ISSUE TITLE
Does KELLER_PA8 need to be retained for non-RBR use?

### ISSUE THREAD

**Issue by matdon17** [nvs-vocabs/R27#7]
It has been decided that were a KELLER_PA8 pressure transducer is incorporated in an RBR pressure sensor, then that sensor should be recorded as and RBR_PRES or RBR_PRES_A as appropriate.  See https://github.com/nvs-vocabs/R27/issues/5 and https://github.com/nvs-vocabs/R27/issues/6

However, there is one instance on Ocean OPS of a float (WMO no. 5906417) that has a KELLER_PA8 alongside an SBE61, rather than as an RBR sensor.  Does KELLER_PA8 need to be retained for this application, or is this an error in Ocean OPS, etc.?

**Comment by vpaba** [comment]
A code for KELLER_PA8 has now been created in [R27](http://vocab.nerc.ac.uk/collection/R27/current/)*. 

This issue can be re-opened and the code deprecated if advised to do so @nvs-vocabs/avtt .

*Please note it may not be visible until 20th Aug 2021, though this is what what it looks like:

> **Id**: KELLER_PA8 
**Pref Label**: Keller PA-8 pressure transducer
**Definition**: A sealed gauge pressure transducer part of the Series 8 pressure sensors range manufactured by Keller.
